micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:secret}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  erp: ${ERP_ITAU:`http://localhost:9091`}

bcb:
  url: ${BCB_URL:`http://localhost:8082`}